name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - run: |
        npm install
        npm test
        npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        EXTERNAL_REPOSITORY: dobladov/dobladov.github.io
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
