name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'
    - run: |
        npm install
        npm test
        npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      env:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: dobladov/dobladov.github.io
        publish_branch: master
        publish_dir: ./public
